"""YAML serialization for comparison reports.

Terminal rendering (Rich tables) lives in the adapters layer. This module
handles only the machine-parseable YAML output, consistent with the
existing split where ``renderers/yaml.py`` serializes workspace artifacts.
"""

from __future__ import annotations

import yaml

from ...domain.comparison import (
    ContentKind,
    FileDiffResult,
    FileReport,
    NodeMatch,
    TreeReport,
)


# ---------------------------------------------------------------------------
# Tree report
# ---------------------------------------------------------------------------


def render_tree_yaml(report: TreeReport) -> str:
    """Serialize a :class:`TreeReport` to YAML."""
    data: dict = {
        "projects": list(report.projects),
        "subtree": report.subtree,
        "summary": {
            "total_nodes": report.summary.total_nodes,
            "in_all": report.summary.in_all,
            "in_some": report.summary.in_some,
            "in_one": report.summary.in_one,
            "directories_matched": report.summary.directories_matched,
            "files_matched": report.summary.files_matched,
        },
        "matches": [_serialize_node(m) for m in report.matches],
    }
    header = (
        "# comparison-tree.yml --- Cross-project architecture comparison.\n"
        "# Generated by `stelion compare tree`.\n\n"
    )
    return header + yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _serialize_node(node: NodeMatch) -> dict:
    entry: dict = {
        "path": node.canonical_path,
        "type": "directory" if node.is_directory else "file",
        "method": node.method.value,
        "similarity": round(node.similarity, 3),
        "present_in": sorted(node.present_in),
        "absent_from": sorted(node.absent_from),
        "resolved": dict(sorted(node.resolved.items())),
    }
    if node.children:
        entry["children"] = [_serialize_node(c) for c in node.children]
    return entry


# ---------------------------------------------------------------------------
# File report
# ---------------------------------------------------------------------------


def render_file_yaml(report: FileReport) -> str:
    """Serialize a :class:`FileReport` to YAML."""
    data: dict = {
        "projects": list(report.projects),
        "summary": {
            "files_compared": report.summary.files_compared,
            "fully_identical": report.summary.fully_identical,
            "with_differences": report.summary.with_differences,
            "with_errors": report.summary.with_errors,
        },
        "results": [_serialize_file_result(r) for r in report.results],
    }
    header = (
        "# comparison-files.yml --- Cross-project file comparison.\n"
        "# Generated by `stelion compare files`.\n\n"
    )
    return header + yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _serialize_file_result(result: FileDiffResult) -> dict:
    entry: dict = {
        "canonical_path": result.canonical_path,
        "actual_paths": dict(sorted(result.actual_paths.items())),
        "present_in": sorted(result.present_in),
        "absent_from": sorted(result.absent_from),
        "content_kind": result.content_kind.value,
    }
    if result.issue:
        entry["issue"] = result.issue

    if result.content_kind == ContentKind.STRUCTURED and result.field_diffs:
        entry["fields"] = [
            {"path": fd.path, "values": dict(sorted(fd.values.items()))}
            for fd in result.field_diffs
        ]

    if result.content_kind == ContentKind.UNSTRUCTURED:
        if result.reference_project is not None:
            entry["reference_project"] = result.reference_project
        if result.variants:
            entry["variants"] = [
                {
                    "projects": sorted(v.projects),
                    "digest": v.digest,
                    "line_count": v.line_count,
                }
                for v in result.variants
            ]
        if result.similarities:
            entry["similarities"] = [
                {
                    "pair": [s.project_a, s.project_b],
                    "score": round(s.score, 3),
                }
                for s in result.similarities
            ]
        if result.reference_diffs:
            entry["reference_diffs"] = [
                {
                    "project": diff.project,
                    "diff_lines": list(diff.diff_lines),
                }
                for diff in result.reference_diffs
            ]

    return entry
