"""Render YAML workspace artifacts: dependencies.yml, projects.yml, environment.yml.

Functions
---------
render_dependency_yaml
    Generate dependencies.yml as a structured YAML file.
render_projects_yaml
    Generate projects.yml as a structured YAML registry.
render_environment
    Generate a shared Conda environment.yml.
"""

from __future__ import annotations

import os
from pathlib import Path

import yaml

from ...domain.dependency import DependencyGraph
from ...domain.environment import EnvironmentSpec
from ...domain.project import ProjectInventory


def render_dependency_yaml(graph: DependencyGraph) -> str:
    """Generate dependencies.yml as a structured YAML file.

    Parameters
    ----------
    graph : DependencyGraph
        Detected and manual dependency edges.

    Returns
    -------
    str
        YAML text with a descriptive header comment.
    """
    data: dict = {}

    if graph.detected:
        data["detected"] = [
            {
                "dependent": e.dependent,
                "dependency": e.dependency,
                "mechanism": e.mechanism.name.lower(),
                "detail": e.detail,
            }
            for e in graph.detected
        ]

    if graph.manual:
        data["manual"] = [
            {
                "dependent": e.dependent,
                "dependency": e.dependency,
                "mechanism": e.mechanism.name.lower(),
                "detail": e.detail,
            }
            for e in graph.manual
        ]

    header = (
        "# dependencies.yml --- Inter-project dependency graph.\n"
        "# Auto-detected edges are regenerated by `stelion workspace sync`.\n"
        "# Manual edges come from stelion.yml.\n\n"
    )
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return header + body


def render_projects_yaml(inventory: ProjectInventory, manifest_dir: Path) -> str:
    """Generate projects.yml as a structured YAML registry.

    Parameters
    ----------
    inventory : ProjectInventory
        Discovered projects with metadata.
    manifest_dir : Path
        Directory containing the workspace manifest, used for relative paths.

    Returns
    -------
    str
        YAML text with a descriptive header comment.
    """
    data: dict = {}
    projects: dict = {}
    for p in sorted(inventory.projects, key=lambda x: x.name):
        entry: dict = {}
        entry["status"] = p.status.value
        if p.description:
            entry["description"] = p.description
        entry["version"] = p.version
        if p.languages:
            entry["languages"] = list(p.languages)
        entry["path"] = os.path.relpath(p.path, manifest_dir)
        if p.github:
            entry["github"] = str(p.github)
        if p.homepage:
            entry["homepage"] = p.homepage
        if p.issue:
            entry["issue"] = p.issue
        projects[p.name] = entry

    data["projects"] = projects

    header = (
        "# projects.yml --- Project registry.\n"
        "# Auto-generated by `stelion workspace sync`.\n\n"
    )
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return header + body


def render_environment(environment: EnvironmentSpec) -> str:
    """Generate a shared Conda environment.yml.

    Parameters
    ----------
    environment : EnvironmentSpec
        Merged environment specification.

    Returns
    -------
    str
        YAML text, prefixed with warning comments if issues were detected.
    """
    data: dict = {"name": environment.name}

    if environment.channels:
        data["channels"] = environment.channels

    deps: list = list(environment.dependencies)
    if environment.pip_dependencies:
        deps.append({"pip": list(environment.pip_dependencies)})

    data["dependencies"] = deps

    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    if not environment.issues:
        return body
    header = "".join(f"# WARNING: {issue}\n" for issue in environment.issues)
    return header + body
