"""Render YAML workspace artifacts: dependencies.yml, projects.yml, environment.yml."""

from __future__ import annotations

import os
from pathlib import Path

import yaml

from ...domain.dependency import DependencyGraph
from ...domain.environment import EnvironmentSpec
from ...domain.project import ProjectInventory


def render_dependency_yaml(graph: DependencyGraph) -> str:
    """Generate dependencies.yml as a structured YAML file."""
    data: dict = {}

    if graph.detected:
        data["detected"] = [
            {
                "dependent": e.dependent,
                "dependency": e.dependency,
                "mechanism": e.mechanism.name.lower(),
                "detail": e.detail,
            }
            for e in graph.detected
        ]

    if graph.manual:
        data["manual"] = [
            {
                "dependent": e.dependent,
                "dependency": e.dependency,
                "mechanism": e.mechanism.name.lower(),
                "detail": e.detail,
            }
            for e in graph.manual
        ]

    header = (
        "# dependencies.yml --- Inter-project dependency graph.\n"
        "# Auto-detected edges are regenerated by `stelion workspace sync`.\n"
        "# Manual edges come from stelion.yml.\n\n"
    )
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return header + body


def render_projects_yaml(inventory: ProjectInventory, manifest_dir: Path) -> str:
    """Generate projects.yml as a structured YAML registry."""
    data: dict = {}
    projects: dict = {}
    for p in sorted(inventory.projects, key=lambda x: x.name):
        entry: dict = {}
        if p.description:
            entry["description"] = p.description
        entry["version"] = p.version
        if p.status:
            entry["status"] = p.status
        if p.languages:
            entry["languages"] = p.languages
        entry["path"] = os.path.relpath(p.path, manifest_dir)
        if p.homepage:
            entry["homepage"] = p.homepage
        projects[p.name] = entry

    data["projects"] = projects

    header = (
        "# projects.yml --- Project registry.\n"
        "# Auto-generated by `stelion workspace sync`.\n\n"
    )
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return header + body


def render_environment(environment: EnvironmentSpec) -> str:
    """Generate a shared Conda environment.yml."""
    data: dict = {"name": environment.name}

    if environment.channels:
        data["channels"] = environment.channels

    deps: list = list(environment.dependencies)
    if environment.pip_dependencies:
        deps.append({"pip": list(environment.pip_dependencies)})

    data["dependencies"] = deps

    return yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
