"""Render YAML workspace artifacts: dependencies.yml, environment.yml."""

from __future__ import annotations

import yaml

from ...domain.dependency import DependencyGraph
from ...domain.environment import EnvironmentSpec


def render_dependency_yaml(graph: DependencyGraph) -> str:
    """Generate dependencies.yml as a structured YAML file."""
    data: dict = {}

    if graph.detected:
        data["detected"] = [
            {
                "dependent": e.dependent,
                "dependency": e.dependency,
                "mechanism": e.mechanism.name.lower(),
                "detail": e.detail,
            }
            for e in graph.detected
        ]

    if graph.manual:
        data["manual"] = [
            {
                "dependent": e.dependent,
                "dependency": e.dependency,
                "mechanism": e.mechanism.name.lower(),
                "detail": e.detail,
            }
            for e in graph.manual
        ]

    if graph.proposed:
        data["proposed"] = [
            {
                "consumer": p.consumer,
                "library": p.library,
                "integration": p.integration,
                "priority": p.priority,
                "notes": p.notes,
            }
            for p in graph.proposed
        ]

    header = (
        "# dependencies.yml --- Inter-project dependency graph.\n"
        "# Auto-detected edges are regenerated by `stelion workspace sync`.\n"
        "# Manual and proposed edges come from stelion.yml.\n\n"
    )
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    return header + body


def render_environment(environment: EnvironmentSpec) -> str:
    """Generate a shared Conda environment.yml."""
    data: dict = {"name": environment.name}

    if environment.channels:
        data["channels"] = environment.channels

    deps: list = list(environment.dependencies)
    if environment.pip_dependencies:
        deps.append({"pip": environment.pip_dependencies})

    data["dependencies"] = deps

    return yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
